### ISSUE TITLE
showFavourites feature is not working

### ISSUE THREAD

**Issue by VenturaLorenzo** [Lekwacious/shopping_app-_getx#1]
You create a ProductGrid with a showFavourites bool var but it is actually never used. How would you implement this feature? if the variable is changed in the parent's page the ProductGrid won't be rebuilt so shouldn't you use a statefull widget or a  Obx in the product_overview_screen ?

**Comment by ashokavarthanan** [comment]
ya its not implement. See my Pull requests and check changes made. its solved.

**Comment by Lekwacious** [comment]
I did not implement it. I was trying to keep the article brief as it was
already becoming long.

**Comment by VenturaLorenzo** [comment]
Great thanks
